### ISSUE TITLE
Upgrading to the latest version?

### ISSUE THREAD

**Issue by exptom** [aws-samples/amazon-cloudfront-access-logs-queries#27]
What is the best way to upgrade to the latest version? I originally deployed it using the deploy button in the readme but I'd like to upgrade to the node18 version without losing any data.

**Comment by steffeng** [comment]
Hi @exptom, deploy the application as you did before as described in [the docs](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-how-to-consume-new-version.html#update-applications). The bucket hasn't changed in the latest template and will be kept as-is, including its content. Even if you delete the application's stack, AWS CloudFormation will not delete a non-empty bucket (see [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html)).

**Comment by exptom** [comment]
Thanks @steffeng I had been looking for that in the docs but failed to find it. I've completed the upgrade :slightly_smiling_face:

**Comment by leecookson** [comment]
If I deployed this stack years ago before the underscore field naming convention changed, will re-deploying beak anything, or will the schema be updated and able to query both pre-upgrade and post-upgrade logs?

really 2 questions: 
how will data be handled for the field name changes, and if we have a fairly recent deploy, will the new fields like `time-to-first-byte` be automatically available for logs already processed, only as far back as the fields were available, of course.

**Comment by steffeng** [comment]
Hi @leecookson, quick answer is: AFAICS it will just work, but please try.

**In gzip files:** the type, and order of the field's in values are delivered as [described in the docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/standard-logs-reference.html). The column names in the first two lines of the CSV are ignored, whether dashes (-) or underscores(_). The names from the AWS Glue table defined in this repo's code are taken. I picked underscores instead of dashes to comply with AWS Glue's [column naming conventions](https://docs.aws.amazon.com/athena/latest/ug/tables-databases-columns-names.html#tables-databases-columns-names-complex-types).

In [2019, seven fields were appended](https://github.com/aws-samples/amazon-cloudfront-access-logs-queries/commit/c76192a2dfd0881ef404a31977aefda26911e34f#diff-1363ef5ce8886100842332c97163aad7934237e1fe49b5d40422b45fdc30f38eR257-R270). If you redeploy the stack, the query of old logs before that change in 2019 without the new fields work, but the columns will appear empty.

**In the columnar format parquet files:** these contain their own schema. Missing columns will appear empty.

Can you create a separate issue if you want to dig deeper if needed?

**Comment by leecookson** [comment]
I'll give this a try on a less critical stack and see what happens.  Thanks for the feedback
